#! /bin/sh

echo "phDatabaseApi.py:"
python phDatabaseApi.py

echo "phController.py:"
python phController.py

echo "pubmedApi.py:"
python pubmedApi.py

echo "phTools.py:"
python phTools.py

echo "phInfo.py:"
python phInfo.py

echo "runBottleServer.py:"
python runBottleServer.py --doctest-only

echo "formatPhDatabase.py:"
python formatPhDatabase.py --doctest-only

echo "updatePhDatabase.py:"
python updatePhDatabase.py --doctest-only

echo "sendEmail.py:"
python sendEmail.py --doctest-only

echo "Done."